name: Deploy Content to ecocanarytest [77264424-6b3c-466e-aca1-16b2daca0c1e]
on: 
  push:
    branches: [ bugbash-3 ]
    paths:
    - '**'
    - '.github/workflows/sentinel-deploy-77264424-6b3c-466e-aca1-16b2daca0c1e.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'eco-connector-test'
      workspaceName: 'ecocanarytest'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_772644246b3c466eaca116b2daca0c1e }}
      contentTypes: 'AnalyticsRule,Parser,Playbook'

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_772644246b3c466eaca116b2daca0c1e }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      uses: juliangruber/sleep-action@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}
      with:
        time: 30s
    
    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_772644246b3c466eaca116b2daca0c1e }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      uses: juliangruber/sleep-action@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure' }}
      with:
        time: 30s
    
    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure'  }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_772644246b3c466eaca116b2daca0c1e }}
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v1

    - name: Read deployment script
      id: deploymentScript
      uses: juliangruber/read-file-action@v1
      with:
        path: '${{ github.workspace }}/.github/workflows/azure-sentinel-deploy.ps1'
    
    - name: Deploy Content to Azure Sentinel
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ steps.deploymentScript.outputs.content }}